export const Data = [
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
  {
    name: "Jessica Yaa Freeman",
    volume: "-",
    itemSold: 129,
    worktime: "32h",
    rating: 4.99,
  },
];
