export const Data = [
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    name: "Jessica Yaa Freeman",
    days: 7,
    time: "32h",
    percentage: "90%",
    clockIn: "8:00am",
    clockOut: "5:00pm",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
];
