export const Data = [
  {
    productName: "Paracetamol 250mg",
    batchId: "#46516161",
    unit: "Pack",
    brandName: "Random",
    itemAge: "1 month",
    expiryStatus: "1 month",
    quantity: 15,
  },
  {
    productName: "Ibuprofen 400mg",
    batchId: "#98236112",
    unit: "Bottle",
    brandName: "PharmaCo",
    itemAge: "3 months",
    expiryStatus: "2 months",
    quantity: 30,
  },
  {
    productName: "Amoxicillin 500mg",
    batchId: "#75216341",
    unit: "Capsule",
    brandName: "MediHealth",
    itemAge: "9 months",
    expiryStatus: "6 months",
    quantity: 50,
  },
  {
    productName: "Aspirin 100mg",
    batchId: "#88123123",
    unit: "Tablet",
    brandName: "HealthLine",
    itemAge: "2 weeks",
    expiryStatus: "1 year",
    quantity: 100,
  },
  {
    productName: "Cetirizine 10mg",
    batchId: "#45123698",
    unit: "Strip",
    brandName: "QuickRelief",
    itemAge: "1 year",
    expiryStatus: "2 weeks",
    quantity: 20,
  },
  {
    productName: "Vitamin D3 1000 IU",
    batchId: "#77156452",
    unit: "Bottle",
    brandName: "Sunshine Supplements",
    itemAge: "8 months",
    expiryStatus: "4 months",
    quantity: 40,
  },
  {
    productName: "Loratadine 10mg",
    batchId: "#36214578",
    unit: "Strip",
    brandName: "AllergyRelief",
    itemAge: "5 months",
    expiryStatus: "3 months",
    quantity: 60,
  },
  {
    productName: "Azithromycin 250mg",
    batchId: "#95135745",
    unit: "Pack",
    brandName: "AntibioticPlus",
    itemAge: "2 weeks",
    expiryStatus: "10 months",
    quantity: 25,
  },
];
