export const Data = [
  {
    id: "58547",
    user: [{ userName: "Jessica Yaa Freeman", email: "jessfreeman@gmail.com" }],
    date: "12/09/2019",
    time: "12:53 PM",
    amount: "34,556",
    type: "Momo",
    status: "Successful",
    products: [
      { name: "Laptop", quantity: 1, price: "₵ 15,000" },
      { name: "Headphones", quantity: 2, price: "₵ 500" },
    ],
  },
  {
    id: "58548",
    user: [{ userName: "John Doe", email: "johndoe@gmail.com" }],
    date: "14/09/2019",
    time: "10:15 AM",
    amount: "12,200",
    type: "Cash",
    status: "Failed",
    products: [
      { name: "Smartphone", quantity: 1, price: "₵ 10,000" },
      { name: "Phone Case", quantity: 2, price: "₵ 200" },
    ],
  },
  {
    id: "58549",
    user: [{ userName: "Jane Smith", email: "janesmith@gmail.com" }],
    date: "15/09/2019",
    time: "02:30 PM",
    amount: "8,100",
    type: "Bank",
    status: "Successful",
    products: [
      { name: "Tablet", quantity: 1, price: "₵ 7,000" },
      { name: "Stylus", quantity: 1, price: "₵ 1,100" },
    ],
  },
  {
    id: "58550",
    user: [{ userName: "Michael Scott", email: "michaelscott@gmail.com" }],
    date: "18/09/2019",
    time: "11:20 AM",
    amount: "40,000",
    type: "Momo",
    status: "Failed",
    products: [{ name: "Monitor", quantity: 2, price: "₵ 20,000" }],
  },
  {
    id: "58551",
    user: [{ userName: "Dwight Schrute", email: "dwightschrute@gmail.com" }],
    date: "19/09/2019",
    time: "09:45 AM",
    amount: "5,000",
    type: "Cash",
    status: "Successful",
    products: [{ name: "Desk", quantity: 1, price: "₵ 5,000" }],
  },
  {
    id: "58552",
    user: [{ userName: "Pam Beesly", email: "pambeesly@gmail.com" }],
    date: "20/09/2019",
    time: "01:30 PM",
    amount: "16,000",
    type: "Bank",
    status: "Successful",
    products: [
      { name: "Printer", quantity: 1, price: "₵ 10,000" },
      { name: "Printer Ink", quantity: 5, price: "₵ 1,200" },
    ],
  },
  {
    id: "58553",
    user: [{ userName: "Stanley Hudson", email: "stanleyhudson@gmail.com" }],
    date: "22/09/2019",
    time: "04:45 PM",
    amount: "7,500",
    type: "Momo",
    status: "Failed",
    products: [{ name: "Chair", quantity: 1, price: "₵ 7,500" }],
  },
  {
    id: "58554",
    user: [{ userName: "Kevin Malone", email: "kevinmalone@gmail.com" }],
    date: "24/09/2019",
    time: "03:10 PM",
    amount: "19,000",
    type: "Bank",
    status: "Successful",
    products: [{ name: "Conference Table", quantity: 1, price: "₵ 19,000" }],
  },
];
