export const endpoints = {
  analytics: "/analytics/",
  inventories: "/inventories/",
  managements: "/managements/",
  login: "/login/",
  logout: "/logout-all/",
  signup: "/user-signup/",
  pharmacySignup: "/pharmacy/",
  inventoryProduct: "/inventories/products/",
  inventorySupplier: "/inventories/suppliers/",
  inventoryPurchase: "/inventories/purchases/",
  inventoryExpiryReports: "/inventories/expiry-reports/",
  inventoryBranchSync: "/inventories/stock-transfers/",
  sales: "/sales/",
};
