export const endpoints = {
  analytics: "/analytics/",
  inventories: "/inventories/",
  managements: "/managements/",
  login: "/login/",
  logout: "/logout/",
  signup: "/user-signup/",
  pharmacy: "/pharmacy/",
  inventoryProduct: "/inventories/products/",
  inventorySupplier: "/inventories/suppliers/",
  inventoryPurchase: "/inventories/purchases/",
  inventoryExpiryReports: "/inventories/expiry-reports/",
  inventoryBranchSync: "/inventories/stock-transfers/",
  sales: "/sales/",
  user: "/user/",
  verifyEmail: "/verify-email",
};
