name: deploy-image

on:
  push:
    branches:
      - deploy

jobs:
  deploy-main-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Generate .env file
      #   run: echo "DB_HOST=SOMESECRET" > ./config/.env && echo "DB_NAME=SOMEPUBKEY" >> ./config/.env && echo "DB_PASSWORD=SOMEURL" >> ./config/.env && echo "DB_PORT=SOMEURL" >> ./config/.env && echo "DEBUG_MODE=SOMEURL" >> ./config/.env

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: curmens/procare_frontend:latest
          platforms: linux/amd64,linux/arm64
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run scripts
        uses: appleboy/ssh-action@master
        timeout-minutes: 600
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_STAGING_KEY }}
          script: |
            cd web
            docker compose pull
            docker compose up --build -d