name: Build and Deploy staging
on:
  push:
    branches:
      - staging
      - config

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy Scripts to Staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_STAGING_KEY }}
          source: "apps/*, Dockerfile, docker-compose.yml, config/*, Dockerfile.dev, manage.py, requirements"
          target: "staging/nnuropay"
          rm: true
      - name: Run scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_STAGING_KEY }}
          script: |
            cd staging
            cp .env nnuropay/
            docker compose -f docker-compose.stage.yml up redis-server order-service --build -d